## List all books
## user:user is the authentication
GET http://localhost:8080/book
Authorization: Basic dXNlcjp1c2Vy

### Get book with id
GET http://localhost:8080/book/1

### Get book by name
GET http://localhost:8080/book/search/name?value=book_22

### Create book
POST http://localhost:8080/book
Content-Type: application/json

{
  "name": "new_book_updated",
  "libraryId": 1
}

### Update book
PUT http://localhost:8080/book/5
Content-Type: application/json

{
  "name": "new_book_updated",
  "libraryId": 1
}

### Delete book
DELETE http://localhost:8080/book/1

###

