SET SCHEMA LIBRARY;
INSERT INTO LIBRARY (ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (LIBRARY_SEQUENCE.nextval, 'First library', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID)
VALUES (BOOK_SEQUENCE.nextval, 'First book', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID)
VALUES (BOOK_SEQUENCE.nextval, 'Second book', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID)
VALUES (BOOK_SEQUENCE.nextval, 'Third book', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID)
VALUES (BOOK_SEQUENCE.nextval, 'Fourth book', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);