SET SCHEMA LIBRARY;
INSERT INTO LIBRARY (ID, NAME, CREATED_AT, UPDATED_AT) VALUES (LIBRARY_SEQUENCE.nextval, 'library_1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID) VALUES (BOOK_SEQUENCE.nextval, 'book_1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID) VALUES (BOOK_SEQUENCE.nextval, 'book_2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID) VALUES (BOOK_SEQUENCE.nextval, 'book_3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);
INSERT INTO BOOK (ID, NAME, CREATED_AT, UPDATED_AT, LIBRARY_ID) VALUES (BOOK_SEQUENCE.nextval, 'book_4', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), LIBRARY_SEQUENCE.currval);